### ISSUE TITLE
Code to Compute the Forward Threshold

### ISSUE THREAD

**Issue by superctj** [deeplearning-wisc/react#1]
Thank you for open-sourcing the code of this great work! I was wondering if you could also release the code that computes the threshold based on p-th percentile activation.

**Comment by sunyiyou** [comment]
Thanks for your interest in our work! I will update the code in a few days. Feel free to remind me if I forgot afterwards!

The code is also quite simple to write if you are willing to. Just collect all the activation values in the penultimate layers of ImageNet and use the NumPy  percentile library.

**Comment by sunyiyou** [comment]
Hi there, I have updated the repo. Simply running 
`python compute_threshold.py 
`
should work

**Comment by superctj** [comment]
Thank you, Yiyou! Happy Chinese New Year!
