### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/CIFAR-10/resnet50/checkpoint_100.pth.tar'

### ISSUE THREAD

**Issue by howell0203** [deeplearning-wisc/react#10]
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/CIFAR-10/resnet50/checkpoint_100.pth.tar'
Thank you for your code. Where can I get this pre-trained model? Do I need to train one?

**Comment by sunyiyou** [comment]
You can use the train_module here https://github.com/sunyiyou/train_module. CIFAR training should be easily finished in 2 hours.
