### ISSUE TITLE
Where is mahalanobis_hyperparams

### ISSUE THREAD

**Issue by syf-fgnb** [deeplearning-wisc/react#4]
Hi, 

Thanks for your excellent work. When I check the code in eval.py, I just wonder where the file of "mahalanobis_hyperparams" locates. I would appreciate it if you could point it out for me.

**Comment by sunyiyou** [comment]
Hi, if you would like to check out the implementation for the Mahalanobis score, here is the repo you can refer to. 
https://github.com/jfc43/informative-outlier-mining

Specifically, you can look into tune_mahalanobis_hyperparams.py.
Hope it helps!
