### ISSUE TITLE
Thank you for sharing this code and I still have some question.

### ISSUE THREAD

**Issue by ZY123-GOOD** [deeplearning-wisc/react#6]

**Comment by ZY123-GOOD** [comment]
We found this paper interesting and thank you for sharing this code. However, we found that the output of the penultimate layer for ID data is also positively skewed distribution (ResNet-50). Indeed, the "clip" operation has more influence on ID data than OOD data, which is different from the assumption in your paper. Do you also find this phenomenon, and could you please show why the ReAct method work?

**Comment by sunyiyou** [comment]
Hi, thanks for your interest in our work!

Actually the claim " the 'clip' operation has more influence on ID data than OOD data" is not justified, if you see Figure 1 in our paper:
ID data has a nice property with nearly constant mean and std, while OOD data is more chaotic. So clipping at a right threshold would not change ID too much, but it reduces the "overly-high" activation value for OOD data.

Our theoretical assumption ID data's distribution is based on the mechanism of Batch-normalization. (So ID follows a rectified Gaussian distribution). Though empirically it may be somewhat biased, it is still less positively skewed than OOD data.

Hope the answer helps.

**Comment by ZY123-GOOD** [comment]
Thank you! Best wishes.



---Original---
From: "Yiyou ***@***.***&gt;
Date: Fri, Apr 29, 2022 05:59 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [deeplearning-wisc/react] Thank you for sharing this code and Istill have some question. (Issue #6)




 
Hi, thanks for your interest in our work!
 
Actually the claim " the 'clip' operation has more influence on ID data than OOD data" is not justified, if you see Figure 1 in our paper:
 ID data has a nice property with nearly constant mean and std, while OOD data is more chaotic. So clipping at a right threshold would not change ID too much, but it reduces the "overly-high" activation value for OOD data.
 
Our theoretical assumption ID data's distribution is based on the mechanism of Batch-normalization. (So ID follows a rectified Gaussian distribution). Though empirically it may be somewhat biased, it is still less positively skewed than OOD data.
 
Hope the answer helps.
